# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UI_presentation_1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UI_presentation_1
  pod 'Charts'
  pod 'RealmSwift'

end
